environment:
  global:
    RANDOM_SEED: 0
  matrix:
    - PYTHON: "C:\\Python27-x64" # latest 2.7.x version
    - PYTHON: "C:\\Python36-x64" # latest 3.6.x version
    - PYTHON: "C:\\Python37-x64" # latest 3.7.x version

cache:
  - .venv -> Makefile

install:
  # Add Make and Python to the PATH
  - copy C:\MinGW\bin\mingw32-make.exe C:\MinGW\bin\make.exe
  - set PATH=%PATH%;C:\MinGW\bin
  - set PATH=%PYTHON%;%PATH%
  - set PATH=%PYTHON%\Scripts;%PATH%
  # Install system dependencies
  - pip install pipenv
  - make doctor
  # Install project dependencies
  - make install

build: off

test_script:
  - make check
  - make test

notifications:
  - provider: Slack
    incoming_webhook:
      secure: pOtkIG6sWisx6PnW52iPzyTGj7q52D12er8ctpwYxs4ASoR4hynEnMPMuvRXlenHj6N6kU3FdO8EBXn79WxfuKGLW8JXhgVUMdAvdEvF4Dk=