environment:
  global:
    RANDOM_SEED: 0
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python36-x64"

cache:
  - .venv -> Makefile

install:
  # Add Make and Python to the PATH
  - copy C:\MinGW\bin\mingw32-make.exe C:\MinGW\bin\make.exe
  - set PATH=%PATH%;C:\MinGW\bin
  - set PATH=%PYTHON%;%PATH%
  - set PATH=%PYTHON%\Scripts;%PATH%
  # Install system dependencies
  - pip install pipenv
  - pip install pathlib2
  - make doctor
  # Install project dependencies
  - make install

build: off

test_script:
  - make check
  - make test

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
